// frontend/react_js/src/board/BoardList.js
import React, { useEffect, useState } from "react";
import axios from "axios";
import { Link, useNavigate } from "react-router-dom";
import SearchBar from "../components/SearchBar";
import styled from "styled-components";
import { useModal } from "../components/ModalProvider";

const Section = styled.div`
  margin: 20px auto;

  button {
    margin: 2px;
    padding: 4px 8px; // 패딩을 줄여서 버튼 크기 조절
    font-size: 0.875rem; // 글자 크기 줄이기
  }
`;

const Container = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const Table = styled.table`
  width: 100%;
  border-collapse: collapse;
  tbody,
  td,
  tfoot,
  th,
  thead,
  tr {
    border-style: double;
    border-width: 3px;
  }
  thead th {
    background-color: #343a406e !important;
  }
  th,
  td {
    padding: 10px;
    text-align: center;
  }

  thead th {
    background-color: #343a40;
    color: white;
  }

  tbody tr:nth-child(odd) {
    background-color: #f9f9f9;
  }

  tbody tr:hover {
    background-color: #f1f1f1;
  }

  td:first-child {
    width: 70%;
  }

  td:nth-child(2),
  td:nth-child(3) {
    width: 15%;
  }

  a {
    color: #007bff;
    text-decoration: none;

    &:hover {
      text-decoration: underline;
    }
  }
`;

const BoardList = () => {
  const navigate = useNavigate();
  const [boardList, setBoardList] = useState([]);
  const [pageList, setPageList] = useState([]);
  const [curPage, setCurPage] = useState(0);
  const [prevBlock, setPrevBlock] = useState(0);
  const [nextBlock, setNextBlock] = useState(0);
  const [lastPage, setLastPage] = useState(0);
  const [search, setSearch] = useState({ page: 1, sk: "", sv: "" });
  const { showModal } = useModal();

  const getBoardList = async () => {
    console.log("서치", search.page);
    if (search.page === curPage) return;
    const queryString = Object.entries(search)
      .map((e) => e.join("="))
      .join("&");
    const resp = await axios
      .get("/board?" + queryString)
      .then((res) => res.data);
    setBoardList(resp.data || []);
    const { endPage, nextBlock, prevBlock, startPage, totalPageCnt } =
      resp.pagination;
    console.log(resp.pagination);
    setCurPage(search.page);
    setPrevBlock(prevBlock);
    setNextBlock(nextBlock);
    setLastPage(totalPageCnt);
    const tmpPages = [];
    for (let i = startPage; i <= endPage; i++) {
      tmpPages.push(i);
    }
    console.log("tempages", tmpPages);
    setPageList(tmpPages);
  };

  const moveToWrite = () => {
    navigate("/write");
  };

  const onClick = (event) => {
    let value = event.target.value;
    setSearch({ ...search, page: value });
    getBoardList();
  };

  const onChange = (event) => {
    const { value, name } = event.target;
    setSearch({ ...search, [name]: value });
  };

  const onSearch = () => {
    if (search.sk === "") {
      showModal("검색조건을 선택해주세요!");
      return;
    } else {
      setSearch({ ...search, page: 1 });
      setCurPage(0);
      getBoardList();
    }
  };

  useEffect(() => {
    getBoardList();
  }, [search]);

  return (
    <div>
      <header className="header">
        <h1>일반게시판</h1>
      </header>
      <div>
        <div className="d-flex justify-content-end">
          <button className="btn btn-primary" onClick={moveToWrite}>
            글쓰기
          </button>
        </div>
        <Container className="container py-4">
          <Table className="table table-hover table-striped">
            <thead>
              <tr>
                <th>제목</th>
                <th>작성자</th>
                <th>등록일</th>
              </tr>
            </thead>
            <tbody>
              {boardList.map((board) => (
                <tr key={board.brdSq}>
                  <td>
                    <Link to={`/board/${board.brdSq}`}>{board.brdTtl}</Link>
                  </td>
                  <td>{board.createdBy}</td>
                  <td>{board.insrtDtm.slice(0, 10)}</td>
                </tr>
              ))}
            </tbody>
          </Table>
          <Section className="pagination-wrapper">
            <ul>
              <button onClick={onClick} value={1} className="btn btn-primary">
                &lt;&lt;
              </button>
              <button
                onClick={onClick}
                value={prevBlock}
                className="btn btn-primary"
              >
                &lt;
              </button>
              {pageList.map((page, index) => (
                <button
                  key={index}
                  onClick={onClick}
                  value={page}
                  className="btn btn-primary"
                >
                  {page}
                </button>
              ))}
              <button
                onClick={onClick}
                value={nextBlock}
                className="btn btn-primary"
              >
                &gt;
              </button>
              <button
                onClick={onClick}
                value={lastPage}
                className="btn btn-primary"
              >
                &gt;&gt;
              </button>
            </ul>
          </Section>
          <br />
          <div className="search-bar">
            <SearchBar onChange={onChange} onSearch={onSearch} />
          </div>
          <br />
        </Container>
      </div>
    </div>
  );
};

export default BoardList;

// frontend/vue_js/src/views/fo/community/board/BoardList.vue
<template>
  <div class="board-list-container">
    <header class="header">
      <h1>일반게시판</h1>
    </header>

    <div class="board-content">
      <div class="search-box">
        <div class="search-area mb-4">
          <select v-model="search.sk" class="search-select">
            <option value="">-선택-</option>
            <option value="title">제목</option>
            <option value="contents">내용</option>
          </select>
          <input
            type="text"
            v-model="search.sv"
            class="search-input"
            @keydown.enter="onSearch"
            placeholder="검색어를 입력하세요"
          />
          <button class="btn btn-primary" @click="onSearch">검색</button>
        </div>
        <div class="d-flex justify-content-end mb-4" v-if="isLoggedIn">
          <router-link class="btn btn-primary" to="/board/write"
            >글쓰기</router-link
          >
        </div>
      </div>
      <div class="table-responsive">
        <table class="table table-hover table-striped">
          <thead>
            <tr>
              <th>제목</th>
              <th>작성자</th>
              <th>등록일</th>
              <th>조회수</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="board in boardList" :key="board.brdSq">
              <td class="title-cell">
                <router-link :to="`/board/${board.brdSq}`">{{
                  board.brdTtl
                }}</router-link>
              </td>
              <td class="small-text">{{ board.createdBy }}</td>
              <td class="small-text">{{ board.insrtDtm.slice(0, 10) }}</td>
              <td class="small-text">{{ board.brdHits }}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="pagination-wrapper">
        <ul class="pagination justify-content-center">
          <li class="page-item" :class="{ disabled: curPage === 1 }">
            <button
              class="page-link"
              @click="goToPage(1)"
              :disabled="curPage === 1"
            >
              &lt;&lt;
            </button>
          </li>
          <li class="page-item" :class="{ disabled: curPage === 1 }">
            <button
              class="page-link"
              @click="goToPage(curPage - 1)"
              :disabled="curPage === 1"
            >
              &lt;
            </button>
          </li>
          <li
            v-for="(page, index) in pageList"
            :key="index"
            class="page-item"
            :class="{ active: curPage === page }"
          >
            <button class="page-link" @click="goToPage(page)">
              {{ page }}
            </button>
          </li>
          <li class="page-item" :class="{ disabled: curPage === lastPage }">
            <button
              class="page-link"
              @click="goToPage(curPage + 1)"
              :disabled="curPage === lastPage"
            >
              &gt;
            </button>
          </li>
          <li class="page-item" :class="{ disabled: curPage === lastPage }">
            <button
              class="page-link"
              @click="goToPage(lastPage)"
              :disabled="curPage === lastPage"
            >
              &gt;&gt;
            </button>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, computed } from "vue";
import { api } from "../../../../axios";
import { showAlert } from "../../../../utill/utillModal";
import { useStore } from "vuex";

const store = useStore();
const member = computed(() => store.getters.getMember);
const isLoggedIn = computed(() => member.value !== null);

const boardList = ref([]);
const pageList = ref([]);
const curPage = ref(1);
const prevBlock = ref(0);
const nextBlock = ref(0);
const lastPage = ref(0);
const search = ref({ page: 1, sk: "", sv: "" });

const getBoardList = async () => {
  const queryString = Object.entries(search.value)
    .map((e) => e.join("="))
    .join("&");
  try {
    const data = await api.$get("/board?" + queryString);
    boardList.value = data.data || [];
    console.log(boardList);
    if (data.pagination) {
      const {
        endPage,
        nextBlock: nextPageBlock,
        prevBlock: previousBlock,
        startPage,
        totalPageCnt,
      } = data.pagination;
      curPage.value = parseInt(search.value.page);
      prevBlock.value = previousBlock > 0 ? previousBlock : 1;
      nextBlock.value =
        nextPageBlock <= totalPageCnt ? nextPageBlock : totalPageCnt;
      lastPage.value = totalPageCnt;
      const tmpPages = [];
      for (let i = startPage; i <= endPage; i++) {
        tmpPages.push(i);
      }
      pageList.value = tmpPages;
    } else {
      console.error("Pagination data is missing.");
    }
  } catch (error) {
    console.error("Failed to fetch board list:", error);
  }
};

const onSearch = () => {
  if (search.value.sk === "" || search.value.sv === "") {
    showAlert("검색 조건과 검색어를 모두 입력하세요.");
    return;
  }
  search.value.page = 1;
  getBoardList();
};

const goToPage = (page) => {
  if (page >= 1 && page <= lastPage.value) {
    search.value.page = page;
    getBoardList();
  }
};

onMounted(() => {
  getBoardList();
});
</script>

<style scoped>
.board-list-container {
  max-width: 1000px;
  margin: 0 auto;
  padding: 20px;
}

.header {
  text-align: center;
  margin-bottom: 20px;
}

.board-content {
  background-color: #fff;
  border-radius: 10px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  padding: 20px;
  text-align: center;
}

.table {
  width: 100%;
  margin-bottom: 20px;
}

.table th,
.table td {
  vertical-align: middle;
}

.title-cell {
  width: 70%;
}

.title-cell:hover {
  cursor: pointer;
}

.title-cell a {
  color: #007bff;
  text-decoration: none;
}

.title-cell a:hover {
  text-decoration: underline;
}

.small-text {
  font-size: 0.875rem;
}

.pagination-wrapper {
  margin-top: 20px;
}

.page-link {
  color: #007bff;
  text-decoration: none;
}

.page-item.active .page-link {
  background-color: #007bff;
  border-color: #007bff;
  color: #fff;
}

.page-item.disabled .page-link {
  pointer-events: none;
  color: #6c757d;
}

.search-area {
  display: flex;
  align-items: center;
  margin-bottom: 20px;
  padding: 20px;
  display: flex;
  justify-content: center;
}

.search-select,
.search-input {
  margin-right: 10px;
  padding: 5px;
}

.btn-primary {
  padding: 5px 10px;
}

.justify-content-end {
  align-items: center;
}
.search-box {
  display: flex;
  justify-content: space-between;
}
</style>
